DROP TABLE IF EXISTS REQUEST_INFORMATION;

CREATE TABLE REQUEST_INFORMATION (
	REQUEST_INFORMATION_ID BIGINT IDENTITY NOT NULL PRIMARY KEY,
	TIMESTAMP DATE,
	IP_ADDRESS VARCHAR(64),
	ENDPOINT VARCHAR(64),
	URL VARCHAR(64),
	METHOD VARCHAR(7)
);
